# **9.데이터프레임 추가 기능**

In [1]:
# 라이브러리 불러오기
import numpy as np
import pandas as pd

In [ ]:
# 데이터 불러오기
path = './../00_data/titanic_train.csv'

df = pd.read_csv(path)
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

## **9.1.apply 함수**
- 사용자 정의 함수를 데이터에 적용하고 싶을 때 사용한다.
- `데이터프레임.apply(함수, axis=0/1)`

In [3]:
df1 = df.copy()

In [5]:
# 성인인지 아닌지 (19세 이상은 성인)

def adult(x):
  if x >= 19:
    return 1
  elif x < 19:
    return 0
  else:
    return np.nan


# def adult(x):
#   if x >= 19:
#     return 1
#   return 0

In [6]:
df1['adult'] = df1['Age'].apply(adult)
df1.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,adult
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,1.0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1.0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1.0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1.0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,1.0
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q,NaN
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,1.0
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S,0.0
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S,1.0
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C,0.0

- 간단한 함수는 lambda로 구현할 수 있다.

In [7]:
# Pclass가 1등급이고, SipSp가 1인 경우 1. 그렇지 않으면 0.
df1['pclass_sibsp_lamda'] = df1.apply(lambda x: 1 if x['Pclass'] == 1 and x['SibSp'] == 1 else 0, axis=1)

df1.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,adult,pclass_sibsp_lamda
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,1.0,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1.0,1
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1.0,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1.0,1
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,1.0,0

## **9.2.문자열 다루기**

|메소드|설명|
|:--|:--|
|`.str.contains(문자열)`|문자열을 포함하고 있는지 유무|
|`.str.replace(기존문자열, 대치문자열)`|문자열 대치|
|`.str.split(문자열, expand=True/False, n=개수)`|특정 문자열을 기준으로 쪼개기|
|`.str.lower()`|소문자로 바꾸기|
|`.str.upper()`|대문자로 바꾸기|

In [8]:
df2 = df.copy()
df2.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [9]:
df2['Name'].str.contains('Miss')

0      False
1      False
2       True
3      False
4      False
       ...
886    False
887     True
888     True
889    False
890    False
Name: Name, Length: 891, dtype: bool

In [10]:
df2[df2['Name'].str.contains('Miss')]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15.0,0,0,330923,8.0292,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
866,867,1,2,"Duran y More, Miss. Asuncion",female,27.0,1,0,SC/PARIS 2149,13.8583,NaN,C
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

In [ ]:
df2['Name'] = df2['Name'].str.replace(',','')
df2.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,Braund Mr. Owen Harris,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,Cumings Mrs. John Bradley (Florence Briggs Tha...,female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,Heikkinen Miss. Laina,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,Futrelle Mrs. Jacques Heath (Lily May Peel),female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,Allen Mr. William Henry,male,35.0,0,0,373450,8.0500,NaN,S

In [12]:
df2['Name'].str.split(' ')

0                            [Braund, Mr., Owen, Harris]
1      [Cumings, Mrs., John, Bradley, (Florence, Brig...
2                              [Heikkinen, Miss., Laina]
3      [Futrelle, Mrs., Jacques, Heath, (Lily, May, P...
4                           [Allen, Mr., William, Henry]
                             ...
886                             [Montvila, Rev., Juozas]
887                     [Graham, Miss., Margaret, Edith]
888        [Johnston, Miss., Catherine, Helen, "Carrie"]
889                            [Behr, Mr., Karl, Howell]
890                               [Dooley, Mr., Patrick]
Name: Name, Length: 891, dtype: object

- `expand=False` 가 기본값이므로 리스트 형태로 반환
  - True: 데이터프레임으로 반환. False: 리스트 형태의 시리즈로 반환

In [ ]:
df2['Name'].str.split(' ', expand=True, n=1)
# n=1은 최대 1번만 나누기

             0                                           1
0       Braund                             Mr. Owen Harris
1      Cumings  Mrs. John Bradley (Florence Briggs Thayer)
2    Heikkinen                                 Miss. Laina
3     Futrelle          Mrs. Jacques Heath (Lily May Peel)
4        Allen                           Mr. William Henry
..         ...                                         ...
886   Montvila                                 Rev. Juozas
887     Graham                        Miss. Margaret Edith
888   Johnston              Miss. Catherine Helen "Carrie"
889       Behr                             Mr. Karl Howell
890     Dooley                                 Mr. Patrick

[891 rows x 2 columns]

In [14]:
# 소문자로 바꾸기
df2['Name'].str.lower()

0                                 braund mr. owen harris
1      cumings mrs. john bradley (florence briggs tha...
2                                  heikkinen miss. laina
3            futrelle mrs. jacques heath (lily may peel)
4                                allen mr. william henry
                             ...
886                                 montvila rev. juozas
887                          graham miss. margaret edith
888              johnston miss. catherine helen "carrie"
889                                 behr mr. karl howell
890                                   dooley mr. patrick
Name: Name, Length: 891, dtype: str

In [15]:
# 대문자로 바꾸기
df2['Name'].str.upper()

0                                 BRAUND MR. OWEN HARRIS
1      CUMINGS MRS. JOHN BRADLEY (FLORENCE BRIGGS THA...
2                                  HEIKKINEN MISS. LAINA
3            FUTRELLE MRS. JACQUES HEATH (LILY MAY PEEL)
4                                ALLEN MR. WILLIAM HENRY
                             ...
886                                 MONTVILA REV. JUOZAS
887                          GRAHAM MISS. MARGARET EDITH
888              JOHNSTON MISS. CATHERINE HELEN "CARRIE"
889                                 BEHR MR. KARL HOWELL
890                                   DOOLEY MR. PATRICK
Name: Name, Length: 891, dtype: str

## **9.3.피벗테이블**
- 엑셀의 피벗테이블처럼 인덱스별 컬럼별 값의 연산을 할 수 있다.
- `pd.pivot_table(데이터명, index=, columns=, values=, aggfunc=)`


- 기본 문법
```
pd.pivot_table(data,
               index=인덱스로 사용할 열,
               columns=열로 사용할 열,
               values=집계할 값,
               aggfunc=집계 함수,
               margins=True) # 전체 행과 열의 합/평균 추가
```

In [16]:
df3 = df.copy()
df3.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

**1) 단일 인덱스, 단일 컬럼, 단일 값**

In [17]:
pd.pivot_table(
                df3,
                index='Sex',
                columns='Pclass',
                values='Survived',
                aggfunc='mean'
               )

Pclass         1         2         3
Sex
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [18]:
pd.pivot_table(
                df3,
                index='Pclass',
                columns='Sex',
                values='Survived',
                aggfunc='mean'
               )

Sex       female      male
Pclass
1       0.968085  0.368852
2       0.921053  0.157407
3       0.500000  0.135447

In [19]:
pd.pivot_table(
                df3,
                index='Sex',
                columns='SibSp',
                values='Survived',
                aggfunc='mean'
               )

SibSp          0         1         2         3         4    5    8
Sex
female  0.787356  0.754717  0.769231  0.363636  0.333333  0.0  0.0
male    0.168203  0.310680  0.200000  0.000000  0.083333  0.0  0.0

- `margins` 옵션을 통해 행과 열 전체의 값도 구할 수 있음

In [ ]:
pd.pivot_table(
                df3,
                index='Sex', # 인덱스로 사용할 열
                columns='Survived', #열로 사용할 열
                values='Age', # 집계할 값
                aggfunc='mean', # 집계 함수
                margins=True
               )

Survived          0          1        All
Sex
female    25.046875  28.847716  27.915709
male      31.618056  27.276022  30.726645
All       30.626179  28.343690  29.699118

In [21]:
pd.pivot_table(
                df3,
                index='Sex',
                columns='Survived',
                values='Age',
                aggfunc=['mean', 'max', 'min']
               )

               mean              max        min
Survived          0          1     0     1    0     1
Sex
female    25.046875  28.847716  57.0  63.0  2.0  0.75
male      31.618056  27.276022  74.0  80.0  1.0  0.42

In [23]:
pd.pivot_table(
                df3,
                index='Sex',
                columns='Survived',
                values='Age',
                aggfunc=['mean', 'max', 'min'],
                margins=True
               )

               mean                         max              min
Survived          0          1        All     0     1   All    0     1   All
Sex
female    25.046875  28.847716  27.915709  57.0  63.0  63.0  2.0  0.75  0.75
male      31.618056  27.276022  30.726645  74.0  80.0  80.0  1.0  0.42  0.42
All       30.626179  28.343690  29.699118  74.0  80.0  80.0  1.0  0.42  0.42

**2) 다중 인덱스, 다중 컬럼, 다중 값**

In [22]:
pd.pivot_table(
                df3,
                index=['Sex','Pclass'],
                columns='Survived',
                values='Age',
                aggfunc='mean'
               )

Survived               0          1
Sex    Pclass
female 1       25.666667  34.939024
       2       36.000000  28.080882
       3       23.818182  19.329787
male   1       44.581967  36.248000
       2       33.369048  16.022000
       3       27.255814  22.274211

In [25]:
pd.pivot_table(
                df3,
                index=['Sex','Pclass'],
                columns=['Survived', 'Embarked'],
                values='Age',
                aggfunc='mean'
               )

Survived               0                                1
Embarked               C          Q          S          C     Q          S
Sex    Pclass
female 1       50.000000        NaN  13.500000  35.675676  33.0  33.619048
       2             NaN        NaN  36.000000  19.142857  30.0  29.091667
       3       20.700000  28.100000  23.688889  11.045455  17.6  22.548387
male   1       43.050000  44.000000  45.362500  36.437500   NaN  36.121667
       2       29.500000  57.000000  33.414474   1.000000   NaN  17.095000
       3       27.555556  28.076923  27.168478  18.488571  29.0  22.933333

**3) pivot_table VS groupby**

| **기능**       | **`pd.pivot_table`**       | **`groupby`**           |
|---------------|---------------------------|-------------------------|
| **목적**      | 행, 열, 값으로 다차원 분석       | 주로 그룹화 및 집계        |
| **출력 형태**   | 피벗 테이블 형태의 `DataFrame` | 그룹화된 `DataFrame` 또는 `Series` |
| **다중 집계 함수** | 지원 (`aggfunc`로 여러 함수 가능) | `agg()`로 여러 함수 가능   |
| **margins 옵션** | 전체 합/평균 등 추가 가능       | 지원하지 않음             |
| **다중 인덱스**   | 행과 열에 다중 인덱스 생성       | 행에만 다중 인덱스 생성      |
| **사용성**     | 행과 열을 동시에 요약 가능       | 주로 행 기준으로 요약      |