# 1.환경 준비

- 기본 **라이브러리**와 대상 **데이터**를 가져와 이후 과정을 준비한다.

In [1]:
# 라이브러리 불러오기
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

warnings.filterwarnings(action='ignore')
%config InlineBackend.figure_format = 'retina'

In [4]:
# airquality.csv
path = './../00_data/airquality.csv'
df = pd.read_csv(path)
df.head()

   Ozone  Solar.R  Wind  Temp  Month  Day
0   41.0    190.0   7.4    67      5    1
1   36.0    118.0   8.0    72      5    2
2   12.0    149.0  12.6    74      5    3
3   18.0    313.0  11.5    62      5    4
4    NaN      NaN  14.3    56      5    5

# 2.데이터 이해

- 분석할 데이터를 **충분히 이해**할 수 있도록 다양한 **탐색** 과정을 수행한다.

In [8]:
df.head()

   Ozone  Solar.R  Wind  Temp  Month  Day
0   41.0    190.0   7.4    67      5    1
1   36.0    118.0   8.0    72      5    2
2   12.0    149.0  12.6    74      5    3
3   18.0    313.0  11.5    62      5    4
4    NaN      NaN  14.3    56      5    5

In [11]:
df.tail()

     Ozone  Solar.R  Wind  Temp  Month  Day
148   30.0    193.0   6.9    70      9   26
149    NaN    145.0  13.2    77      9   27
150   14.0    191.0  14.3    75      9   28
151   18.0    131.0   8.0    76      9   29
152   20.0    223.0  11.5    68      9   30

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 153 entries, 0 to 152
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Ozone    116 non-null    float64
 1   Solar.R  146 non-null    float64
 2   Wind     153 non-null    float64
 3   Temp     153 non-null    int64
 4   Month    153 non-null    int64
 5   Day      153 non-null    int64
dtypes: float64(3), int64(3)
memory usage: 7.3 KB

In [12]:
df.describe()

            Ozone     Solar.R        Wind        Temp       Month         Day
count  116.000000  146.000000  153.000000  153.000000  153.000000  153.000000
mean    42.129310  185.931507    9.957516   77.882353    6.993464   15.803922
std     32.987885   90.058422    3.523001    9.465270    1.416522    8.864520
min      1.000000    7.000000    1.700000   56.000000    5.000000    1.000000
25%     18.000000  115.750000    7.400000   72.000000    6.000000    8.000000
50%     31.500000  205.000000    9.700000   79.000000    7.000000   16.000000
75%     63.250000  258.750000   11.500000   85.000000    8.000000   23.000000
max    168.000000  334.000000   20.700000   97.000000    9.000000   31.000000

In [13]:
df.corr()

            Ozone   Solar.R      Wind      Temp     Month       Day
Ozone    1.000000  0.348342 -0.601547  0.698360  0.164519 -0.013226
Solar.R  0.348342  1.000000 -0.056792  0.275840 -0.075301 -0.150275
Wind    -0.601547 -0.056792  1.000000 -0.457988 -0.178293  0.027181
Temp     0.698360  0.275840 -0.457988  1.000000  0.420947 -0.130593
Month    0.164519 -0.075301 -0.178293  0.420947  1.000000 -0.007962
Day     -0.013226 -0.150275  0.027181 -0.130593 -0.007962  1.000000

# 3.데이터 전처리

- **전처리** 과정을 통해 머신러닝 알고리즘에 사용할 수 있는 형태의 데이터를 준비한다.

**1) 결측치 처리**

- 결측치가 있으면 제거하거나 적절한 값으로 채운다.

In [14]:
df.isna().sum()

Ozone      37
Solar.R     7
Wind        0
Temp        0
Month       0
Day         0
dtype: int64

In [15]:
# 전날 값으로 결측치 채우기

df.ffill(inplace=True)

df.isnull().sum()

Ozone      0
Solar.R    0
Wind       0
Temp       0
Month      0
Day        0
dtype: int64

**2) 변수 제거**

- 분석에 의미가 없다고 판단되는 변수는 제거한다.

In [16]:
drop_cols = ['Month', 'Day']
df.drop(drop_cols, axis=1, inplace=True)
df.head()

   Ozone  Solar.R  Wind  Temp
0   41.0    190.0   7.4    67
1   36.0    118.0   8.0    72
2   12.0    149.0  12.6    74
3   18.0    313.0  11.5    62
4   18.0    313.0  14.3    56

**3) x, y 분리**

- 우선 target 변수를 명확히 지정한다.
- target을 제외한 나머지 변수들 데이터는 X로 선언한다.
- target 변수 데이터는 y로 선언한다.
- 이 결과로 만들어진 X는 데이터프레임, y는 시리즈가 된다.
- 이후 모든 작업은 X, y를 대상으로 진행한다.

In [17]:
target = 'Ozone'

# 데이터 분류
X = df.drop(target, axis=1)
y = df[target]

# y = df.loc[:,target]

**4) 학습용, 평가용 데이터 분리**

- 학습용, 평가용 데이터를 적절한 비율로 분리한다.
- 반복 실행 시 동일한 결과를 얻기 위해 random_state 옵션을 지정한다.

In [19]:
from sklearn.model_selection import train_test_split

# 7:3
X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    train_size=0.7,
                                                    random_state=1)

# 4.모델링

- 본격적으로 모델을 **선언**하고 **학습**하고 **평가**하는 과정을 진행한다.
- 우선 **회귀** 문제인지 **분류** 문제인지 명확히 구분한다.

- 회귀 문제 인가? 분류 문제인가?
- 회귀인지 분류인지에 따라 사용할 알고리즘과 평가 방법이 달라진다.
- 다음 알고리즘 사용
    - 알고리즘: LinearRegression

In [20]:
# 1. 라이브러리 불러오기

from sklearn.linear_model import LinearRegression

In [21]:
# 2. 선언하기

model = LinearRegression()

In [22]:
# 3. 학습하기

model.fit(X_train, y_train)

LinearRegression()

In [ ]:
# 예측하기
y_pred = model.predict(X_test)

# 5.회귀 성능 평가

- 다양한 성능 지표로 회귀 모델 성능을 평가한다.

**1) MAE(Mean Absolute Error)**


$$\large MAE=\frac{1}{n}\sum_{i=1}^{n}|y_{i}-\hat{y}_{i}|$$

In [25]:
# MAE : 절대값을 더해서 평균 (Mean Absolute Error)

from sklearn.metrics import mean_absolute_error

# 성능 평가
print('MAE : ', mean_absolute_error(y_test, y_pred) )

MAE :  18.4943614280681

**2) MSE(Mean Squared Error)**

$$\large MSE=\frac{1}{n}\sum_{i=1}^{n}(y_{i}-\hat{y}_{i})^2$$

In [26]:
from sklearn.metrics import mean_squared_error

# 성능 평가
print('MSE : ', mean_squared_error(y_test, y_pred) )

MSE :  571.5185565872267

**3) RMSE(Root Mean Squared Error)**


$$\large RMSE=\sqrt{\frac{1}{n}\sum_{i=1}^{n}(y_{i}-\hat{y}_{i})^2}$$

In [27]:
from sklearn.metrics import root_mean_squared_error

# 성능 평가
print('RMSE : ', root_mean_squared_error(y_test, y_pred)  )

RMSE :  23.90645428722601

**4) MAPE(Mean Absolute Percentage Error)**

$$\large MAPE=\frac{1}{n}\sum_{i=1}^{n}\left |\frac{y_{i}-\hat{y}_{i}}{y_{i}}\right |$$

In [30]:
from sklearn.metrics import mean_absolute_percentage_error

# 성능 평가
print('MAPE : ', mean_absolute_percentage_error(y_test, y_pred) )

MAPE :  0.7009695876098733

**5) R2-Score**

$$\large R^2=1-\frac{SSE}{SST}=1-\frac{\sum_{i=1}^{n}(y_{i}-\hat{y}_{i})^2}{\sum_{i=1}^{n}(y_{i}-\bar{y}_{i})^2}$$

In [31]:
from sklearn.metrics import r2_score
# R2-score
print('R2-Score : ', r2_score(y_test, y_pred))

R2-Score :  0.4361454419683256

- 다음과 같이 score() 메소드를 사용해 R2를 확인할 수 있다.

In [32]:
model.score(X_test, y_test)

0.4361454419683256