# **8.데이터프레임 날짜 다루기**

In [50]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## **8.1.문자형을 날짜형으로 변경**
- 날짜가 문자형으로 되어있다면 날짜형으로 변경해야 여러가지 날짜 계산을 할 수 있다.
- `pd.to_datetime(컬럼, format='날짜 형식')`
- 시간 지정자 참고 : [링크](https://steadiness-193.tistory.com/171#google_vignette)

|형식|설명|
|:--|:--|
|%Y|0을 채운 4자리 연도|
|%y|0을 채운 2자리 연도|
|%m|0을 채운 월|
|%d|0을 채운 일|
|%H|0을 채운 시간|
|%M|0을 채운 분|
|%S|0을 채운 초|

In [51]:
path = 'data/temperatures.csv'

data = pd.read_csv(path)

In [52]:
df = data.copy()

df.head()

         Date  Temp
0  1981-01-01  20.7
1  1981-01-02  17.9
2  1981-01-03  18.8
3  1981-01-04  14.6
4  1981-01-05  15.8

In [53]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3650 entries, 0 to 3649
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    3650 non-null   str
 1   Temp    3650 non-null   float64
dtypes: float64(1), str(1)
memory usage: 57.2 KB

In [54]:
pd.to_datetime(df['Date'], format="%Y-%m-%d")

0      1981-01-01
1      1981-01-02
2      1981-01-03
3      1981-01-04
4      1981-01-05
          ...
3645   1990-12-27
3646   1990-12-28
3647   1990-12-29
3648   1990-12-30
3649   1990-12-31
Name: Date, Length: 3650, dtype: datetime64[us]

In [55]:
df['Date1'] = pd.to_datetime(df['Date'], format="%Y-%m-%d")
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3650 entries, 0 to 3649
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    3650 non-null   str
 1   Temp    3650 non-null   float64
 2   Date1   3650 non-null   datetime64[us]
dtypes: datetime64[us](1), float64(1), str(1)
memory usage: 85.7 KB

In [56]:
df.head()

         Date  Temp      Date1
0  1981-01-01  20.7 1981-01-01
1  1981-01-02  17.9 1981-01-02
2  1981-01-03  18.8 1981-01-03
3  1981-01-04  14.6 1981-01-04
4  1981-01-05  15.8 1981-01-05

## **8.2.날짜를 원하는 형식으로 변경**
`데이터컬럼.dt.strftime(날짜형식)`

In [57]:
# 4자리 년-월
df['Date1'].dt.strftime('%Y-%m')

0       1981-01
1       1981-01
2       1981-01
3       1981-01
4       1981-01
         ...
3645    1990-12
3646    1990-12
3647    1990-12
3648    1990-12
3649    1990-12
Name: Date1, Length: 3650, dtype: str

In [58]:
# 년-월  시간:분
df['Date1'].dt.strftime('%Y-%m %H:%M')

0       1981-01 00:00
1       1981-01 00:00
2       1981-01 00:00
3       1981-01 00:00
4       1981-01 00:00
            ...
3645    1990-12 00:00
3646    1990-12 00:00
3647    1990-12 00:00
3648    1990-12 00:00
3649    1990-12 00:00
Name: Date1, Length: 3650, dtype: str

## **8.3.dt 연산자**

|연산자|설명|
|:--|:--|
|year|연도|
|month|월|
|day|일|
|dayofweek|요일(0-월요일, 6-일요일)|
|day_name()|요일을 문자열로|

In [59]:
df['year'] = df['Date1'].dt.year
df['month'] = df['Date1'].dt.month
df['day'] = df['Date1'].dt.day
df['dayofweek'] = df['Date1'].dt.dayofweek
df['dayname'] = df['Date1'].dt.day_name()

In [60]:
df.head()

         Date  Temp      Date1  year  month  day  dayofweek   dayname
0  1981-01-01  20.7 1981-01-01  1981      1    1          3  Thursday
1  1981-01-02  17.9 1981-01-02  1981      1    2          4    Friday
2  1981-01-03  18.8 1981-01-03  1981      1    3          5  Saturday
3  1981-01-04  14.6 1981-01-04  1981      1    4          6    Sunday
4  1981-01-05  15.8 1981-01-05  1981      1    5          0    Monday

## **8.4.날짜 계산**
- day 연산: `pd.Timedelta(day=숫자)`
- month 연산: `DateOffset(months=숫자)`
- year 연산: `DateOffset(years=숫자)`

In [61]:
# 1일 후
df['plus_day1'] = df['Date1'] + pd.Timedelta(days=1)
df.head()

,Date,Temp,Date1,year,month,day,dayofweek,dayname,plus_day1
0,1981-01-01,20.7,1981-01-01,1981,1,1,3,Thursday,1981-01-02
1,1981-01-02,17.9,1981-01-02,1981,1,2,4,Friday,1981-01-03
2,1981-01-03,18.8,1981-01-03,1981,1,3,5,Saturday,1981-01-04
3,1981-01-04,14.6,1981-01-04,1981,1,4,6,Sunday,1981-01-05
4,1981-01-05,15.8,1981-01-05,1981,1,5,0,Monday,1981-01-06

In [62]:
# 7일 후
df['plus_day7'] = df['Date1'] + pd.Timedelta(days=7)
df.head()

,Date,Temp,Date1,year,month,day,dayofweek,dayname,plus_day1,plus_day7
0,1981-01-01,20.7,1981-01-01,1981,1,1,3,Thursday,1981-01-02,1981-01-08
1,1981-01-02,17.9,1981-01-02,1981,1,2,4,Friday,1981-01-03,1981-01-09
2,1981-01-03,18.8,1981-01-03,1981,1,3,5,Saturday,1981-01-04,1981-01-10
3,1981-01-04,14.6,1981-01-04,1981,1,4,6,Sunday,1981-01-05,1981-01-11
4,1981-01-05,15.8,1981-01-05,1981,1,5,0,Monday,1981-01-06,1981-01-12

In [63]:
# 1달 후
from pandas.tseries.offsets import DateOffset

df['plus_month1'] = df['Date1'] + DateOffset(months=1)
df.head()

,Date,Temp,Date1,year,month,day,dayofweek,dayname,plus_day1,plus_day7,plus_month1
0,1981-01-01,20.7,1981-01-01,1981,1,1,3,Thursday,1981-01-02,1981-01-08,1981-02-01
1,1981-01-02,17.9,1981-01-02,1981,1,2,4,Friday,1981-01-03,1981-01-09,1981-02-02
2,1981-01-03,18.8,1981-01-03,1981,1,3,5,Saturday,1981-01-04,1981-01-10,1981-02-03
3,1981-01-04,14.6,1981-01-04,1981,1,4,6,Sunday,1981-01-05,1981-01-11,1981-02-04
4,1981-01-05,15.8,1981-01-05,1981,1,5,0,Monday,1981-01-06,1981-01-12,1981-02-05

In [64]:
# 2년 전
df['minus_year2'] = df['Date1'] - DateOffset(years=2)
df.head()

,Date,Temp,Date1,year,month,day,dayofweek,dayname,plus_day1,plus_day7,plus_month1,minus_year2
0,1981-01-01,20.7,1981-01-01,1981,1,1,3,Thursday,1981-01-02,1981-01-08,1981-02-01,1979-01-01
1,1981-01-02,17.9,1981-01-02,1981,1,2,4,Friday,1981-01-03,1981-01-09,1981-02-02,1979-01-02
2,1981-01-03,18.8,1981-01-03,1981,1,3,5,Saturday,1981-01-04,1981-01-10,1981-02-03,1979-01-03
3,1981-01-04,14.6,1981-01-04,1981,1,4,6,Sunday,1981-01-05,1981-01-11,1981-02-04,1979-01-04
4,1981-01-05,15.8,1981-01-05,1981,1,5,0,Monday,1981-01-06,1981-01-12,1981-02-05,1979-01-05

## **8.5.기간 이동 계산**
- 시간에 따라 변화하는 데이터의 추세를 파악하기 위해 사용되는 통계 기법

`컬럼.rolling().집계함수`

In [65]:
df1 = data.copy()
df1.head()

         Date  Temp
0  1981-01-01  20.7
1  1981-01-02  17.9
2  1981-01-03  18.8
3  1981-01-04  14.6
4  1981-01-05  15.8

In [66]:
# 7일 이동평균
df1['ma7'] = df1['Temp'].rolling(7).mean()
df1.head(10)

         Date  Temp        ma7
0  1981-01-01  20.7        NaN
1  1981-01-02  17.9        NaN
2  1981-01-03  18.8        NaN
3  1981-01-04  14.6        NaN
4  1981-01-05  15.8        NaN
5  1981-01-06  15.8        NaN
6  1981-01-07  15.8  17.057143
7  1981-01-08  17.4  16.585714
8  1981-01-09  21.8  17.142857
9  1981-01-10  20.0  17.314286

In [67]:
# 30일 이동 평균
df1['ma30'] = df1['Temp'].rolling(30).mean()
df1.head(30)

          Date  Temp        ma7   ma30
0   1981-01-01  20.7        NaN    NaN
1   1981-01-02  17.9        NaN    NaN
2   1981-01-03  18.8        NaN    NaN
3   1981-01-04  14.6        NaN    NaN
4   1981-01-05  15.8        NaN    NaN
5   1981-01-06  15.8        NaN    NaN
6   1981-01-07  15.8  17.057143    NaN
7   1981-01-08  17.4  16.585714    NaN
8   1981-01-09  21.8  17.142857    NaN
9   1981-01-10  20.0  17.314286    NaN
10  1981-01-11  16.2  17.542857    NaN
11  1981-01-12  13.3  17.185714    NaN
12  1981-01-13  16.7  17.314286    NaN
13  1981-01-14  21.5  18.128571    NaN
14  1981-01-15  25.0  19.214286    NaN
15  1981-01-16  20.7  19.057143    NaN
16  1981-01-17  20.6  19.142857    NaN
17  1981-01-18  24.8  20.371429    NaN
18  1981-01-19  17.7  21.000000    NaN
19  1981-01-20  15.5  20.828571    NaN
20  1981-01-21  18.2  20.357143    NaN
21  1981-01-22  12.1  18.514286    NaN
22  1981-01-23  14.4  17.614286    NaN
23  1981-01-24  16.0  16.957143    NaN
24  1981-01-25  16.5  15.771429    NaN
25  1981-01-26  18.7  15.914286    NaN
26  1981-01-27  19.4  16.471429    NaN
27  1981-01-28  17.2  16.328571    NaN
28  1981-01-29  15.5  16.814286    NaN
29  1981-01-30  15.1  16.914286  17.79

- 평균 외에 합계, 최솟값, 최댓값 등 다양한 연산이 가능하다.

In [ ]:
# 7일 동안 합계
df1['Temp'].rolling(7).sum().head(10)

In [ ]:
# 7일 동안 최댓값
df1['Temp'].rolling(7).max().head(20)

In [ ]:
# 7일 동안 최솟값
df1['Temp'].rolling(7).min().head(20)