# [실습] 데이터프레임 조회 (1)

1) pandas 라이브러리를 pd 별칭을 주어 불러오세요.

In [2]:
import pandas as pd
import numpy as np

2) 다음 파일을 읽어 tip 데이터프레임을 만드세요.
- 파일 : 'tips.csv'

In [3]:
path = '../../강의코드/data/tips.csv'
tip = pd.read_csv(path)
tip.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

3) 범주형 값을 갖는 day 열에 어떤 값들이 몇 개씩 있는 지 확인하세요.

In [4]:
tip['day'].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

4) total_bill 열만 확인하세요.

In [5]:
tip[['total_bill']]

     total_bill
0         16.99
1         10.34
2         21.01
3         23.68
4         24.59
..          ...
239       29.03
240       27.18
241       22.67
242       17.82
243       18.78

[244 rows x 1 columns]

5) tip, total_bill 열만 확인하세요.

In [6]:
tip[['tip', 'total_bill']]

      tip  total_bill
0    1.01       16.99
1    1.66       10.34
2    3.50       21.01
3    3.31       23.68
4    3.61       24.59
..    ...         ...
239  5.92       29.03
240  2.00       27.18
241  2.00       22.67
242  1.75       17.82
243  3.00       18.78

[244 rows x 2 columns]

6) tip, total_bill 열의 상위 10개 행만 확인하세요.

In [7]:
tip[['tip', 'total_bill']].head(10)

    tip  total_bill
0  1.01       16.99
1  1.66       10.34
2  3.50       21.01
3  3.31       23.68
4  3.61       24.59
5  4.71       25.29
6  2.00        8.77
7  3.12       26.88
8  1.96       15.04
9  3.23       14.78

7) total_bill 평균을 total_mean으로 선언하고 그 값을 확인하세요.

In [8]:
# total_bill 평균
total_mean = tip['total_bill'].mean()

# 확인
total_mean

np.float64(19.78594262295082)

8) 다음 요구사항에 따라 구문을 순서대로 작성하고 확인하세요.

- tip 데이터프레임 total_bill이 45.0 이상, tip이 6.0 이상인 행을 good 데이터프레임으로 선언하세요.
- good 데이터프레임 인덱스를 초기화하세요.(단, 기존 인덱스는 제거)
- good 데이터프레임을 확인하세요.

In [9]:
# total_bill 45.0 이상, tip 6.0 이상
good = tip[(tip['total_bill'] >= 45.0) & (tip['tip'] >= 6.0)]

# 인덱스 초기화
good.reset_index(drop=True, inplace=True)

# 확인
good.head()

   total_bill    tip   sex smoker  day    time  size
0       48.27   6.73  Male     No  Sat  Dinner     4
1       50.81  10.00  Male    Yes  Sat  Dinner     3
2       48.33   9.00  Male     No  Sat  Dinner     4

9) tip 데이터프레임 total_bill이 평균 이상인 행을 good2 데이터프레임으로 선언하고 확인하세요.

In [10]:
# total_bill이 평균 이상
total_mean = tip['total_bill'].mean()
good2 = tip[(tip['total_bill'] >= total_mean)]

# 확인
good2.head()

   total_bill   tip     sex smoker  day    time  size
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
5       25.29  4.71    Male     No  Sun  Dinner     4
7       26.88  3.12    Male     No  Sun  Dinner     4