# 3.데이터프레임 조회

In [1]:
import pandas as pd
import numpy as np

## 3.1.데이터 읽어오기

In [4]:
path = './../00_data/tips.csv'
tips = pd.read_csv(path)

tips.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

## 3.2.특정 열 조회

- **df.loc[ : , [열 이름1, 열 이름2,...]]** 형태로 조회할 열 이름을 리스트로 지정한다.
- 조회할 열이 하나면 리스트 형태가 아니어도 된다.
- 열 부분은 생략할 수 있었지만, **행 부분을 생략할 수는 없다.**
- 하지만 **df[[열 이름1, 열 이름2,...]]** 형태로 인덱서를 생략함이 일반적이다.

In [5]:
# total_bill 열 조회
tips['total_bill']

0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64

In [ ]:
# total_bill 열 조회
tips[['total_bill']]

     total_bill
0         16.99
1         10.34
2         21.01
3         23.68
4         24.59
..          ...
239       29.03
240       27.18
241       22.67
242       17.82
243       18.78

[244 rows x 1 columns]

In [7]:
tips.loc[:,['total_bill']]

     total_bill
0         16.99
1         10.34
2         21.01
3         23.68
4         24.59
..          ...
239       29.03
240       27.18
241       22.67
242       17.82
243       18.78

[244 rows x 1 columns]

In [ ]:
# tip, total_bill 열 조회 (2개)

# 방법 2: loc 사용 시 행은 : 로 전체 선택, 열은 두 번째 인자
tips.loc[:, ['tip', 'total_bill']]

      tip  total_bill
0    1.01       16.99
1    1.66       10.34
2    3.50       21.01
3    3.31       23.68
4    3.61       24.59
..    ...         ...
239  5.92       29.03
240  2.00       27.18
241  2.00       22.67
242  1.75       17.82
243  3.00       18.78

[244 rows x 2 columns]

In [ ]:
# tip, total_bill 열 조회 (2개)

# 방법 1: 대괄호로 직접 열 선택 (권장)
tips[['tip', 'total_bill']]

      tip  total_bill
0    1.01       16.99
1    1.66       10.34
2    3.50       21.01
3    3.31       23.68
4    3.61       24.59
..    ...         ...
239  5.92       29.03
240  2.00       27.18
241  2.00       22.67
242  1.75       17.82
243  3.00       18.78

[244 rows x 2 columns]

**<연습문제>**

[문1] tip 데이터프레임에 대해 아래 요구사항에 맞는 구문을 작성하고 실행하세요.

In [14]:
# 상위 5개 행 조회
tips.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [17]:
# tip 열만 조회

tips[['tip']]

      tip
0    1.01
1    1.66
2    3.50
3    3.31
4    3.61
..    ...
239  5.92
240  2.00
241  2.00
242  1.75
243  3.00

[244 rows x 1 columns]

In [18]:
# tip, day, time 열만 조회

tips[['tip','day','time']]

      tip   day    time
0    1.01   Sun  Dinner
1    1.66   Sun  Dinner
2    3.50   Sun  Dinner
3    3.31   Sun  Dinner
4    3.61   Sun  Dinner
..    ...   ...     ...
239  5.92   Sat  Dinner
240  2.00   Sat  Dinner
241  2.00   Sat  Dinner
242  1.75   Sat  Dinner
243  3.00  Thur  Dinner

[244 rows x 3 columns]

In [19]:
# tip, day, time 열만 tip 열 기준으로 내림차순 정렬해서 조회

tips[['tip','day','time']].sort_values(by='tip',ascending=False)

       tip   day    time
170  10.00   Sat  Dinner
212   9.00   Sat  Dinner
23    7.58   Sat  Dinner
59    6.73   Sat  Dinner
141   6.70  Thur   Lunch
..     ...   ...     ...
0     1.01   Sun  Dinner
111   1.00   Sat  Dinner
92    1.00   Fri  Dinner
67    1.00   Sat  Dinner
236   1.00   Sat  Dinner

[244 rows x 3 columns]

## 3.3.열 범위 조회

- 범위 조회는 **df.loc[:, 열 이름1:열 이름2]** 형태로 조회한다.
- 범위는 하나만 지정할 수 있어 리스트가 될 수 없으니 대괄호를 사용하지 않는다.
- 범위 마지막 열도 조회 대상에 포함된다.

In [20]:
# tips.head()

# sex ~ time 열 조회
tips.loc[:, 'sex':'time']

        sex smoker   day    time
0    Female     No   Sun  Dinner
1      Male     No   Sun  Dinner
2      Male     No   Sun  Dinner
3      Male     No   Sun  Dinner
4    Female     No   Sun  Dinner
..      ...    ...   ...     ...
239    Male     No   Sat  Dinner
240  Female    Yes   Sat  Dinner
241    Male    Yes   Sat  Dinner
242    Male     No   Sat  Dinner
243  Female     No  Thur  Dinner

[244 rows x 4 columns]

## 3.4.조건으로 조회

- **df.loc[조건]** 형태로 조건을 지정해 조건에 만족하는 데이터만 조회할 수 있다.

**1) 단일 조건 조회**

In [22]:
# 조건: tips['tip'] > 6.0

tips.loc[tips['tip']>6.0,:]

     total_bill    tip     sex smoker   day    time  size
23        39.42   7.58    Male     No   Sat  Dinner     4
59        48.27   6.73    Male     No   Sat  Dinner     4
141       34.30   6.70    Male     No  Thur   Lunch     6
170       50.81  10.00    Male    Yes   Sat  Dinner     3
183       23.17   6.50    Male    Yes   Sun  Dinner     4
212       48.33   9.00    Male     No   Sat  Dinner     4
214       28.17   6.50  Female    Yes   Sat  Dinner     3

- 조건을 변수로 선언해 사용할 수 있다.

In [23]:
cond = tips['tip']>6.0

tips.loc[cond,:]

     total_bill    tip     sex smoker   day    time  size
23        39.42   7.58    Male     No   Sat  Dinner     4
59        48.27   6.73    Male     No   Sat  Dinner     4
141       34.30   6.70    Male     No  Thur   Lunch     6
170       50.81  10.00    Male    Yes   Sat  Dinner     3
183       23.17   6.50    Male    Yes   Sun  Dinner     4
212       48.33   9.00    Male     No   Sat  Dinner     4
214       28.17   6.50  Female    Yes   Sat  Dinner     3

**2) 여러 조건 조회**

- [ ]안에 조건을 여러개 연결할 때 **and와 or 대신에 &와 |** 를 사용해야 한다.
- 그리고 각 조건들은 **(조건1) & (조건2)** 형태로 **괄호**로 묶어야 한다.

In [25]:
# tip 열 값이 6.0 보다 크고, day가 Sat 조회

con = (tips['tip'] > 6.0) & (tips['day']=='Sat')

tips.loc[cond]

     total_bill    tip     sex smoker   day    time  size
23        39.42   7.58    Male     No   Sat  Dinner     4
59        48.27   6.73    Male     No   Sat  Dinner     4
141       34.30   6.70    Male     No  Thur   Lunch     6
170       50.81  10.00    Male    Yes   Sat  Dinner     3
183       23.17   6.50    Male    Yes   Sun  Dinner     4
212       48.33   9.00    Male     No   Sat  Dinner     4
214       28.17   6.50  Female    Yes   Sat  Dinner     3

In [26]:
# tip 열 값이 6.0 보다 크거나 또는 day가 Sat 조회

con = (tips['tip'] > 6.0) | (tips['day']=='Sat')

tips.loc[cond]

     total_bill    tip     sex smoker   day    time  size
23        39.42   7.58    Male     No   Sat  Dinner     4
59        48.27   6.73    Male     No   Sat  Dinner     4
141       34.30   6.70    Male     No  Thur   Lunch     6
170       50.81  10.00    Male    Yes   Sat  Dinner     3
183       23.17   6.50    Male    Yes   Sun  Dinner     4
212       48.33   9.00    Male     No   Sat  Dinner     4
214       28.17   6.50  Female    Yes   Sat  Dinner     3

**3) 편리한 isin(), between() 메소드**

- **isin([값1, 값2,..., 값n])**: 값1 또는 값2 또는...값n인 데이터만 조회한다.

In [28]:
# 값 나열 (day가 Sat 또는 Sun)
# tips.loc[tips['day'].isin(['Sat','Sun']),:]
tips.loc[tips['day'].isin(['Sat','Sun'])]

     total_bill   tip     sex smoker  day    time  size
0         16.99  1.01  Female     No  Sun  Dinner     2
1         10.34  1.66    Male     No  Sun  Dinner     3
2         21.01  3.50    Male     No  Sun  Dinner     3
3         23.68  3.31    Male     No  Sun  Dinner     2
4         24.59  3.61  Female     No  Sun  Dinner     4
..          ...   ...     ...    ...  ...     ...   ...
238       35.83  4.67  Female     No  Sat  Dinner     3
239       29.03  5.92    Male     No  Sat  Dinner     3
240       27.18  2.00  Female    Yes  Sat  Dinner     2
241       22.67  2.00    Male    Yes  Sat  Dinner     2
242       17.82  1.75    Male     No  Sat  Dinner     2

[163 rows x 7 columns]

- 위 구문은 다음과 같은 의미를 갖는다.

In [29]:
tips.loc[(tips['day']=='Sat') | (tips['day']=='Sun')]

     total_bill   tip     sex smoker  day    time  size
0         16.99  1.01  Female     No  Sun  Dinner     2
1         10.34  1.66    Male     No  Sun  Dinner     3
2         21.01  3.50    Male     No  Sun  Dinner     3
3         23.68  3.31    Male     No  Sun  Dinner     2
4         24.59  3.61  Female     No  Sun  Dinner     4
..          ...   ...     ...    ...  ...     ...   ...
238       35.83  4.67  Female     No  Sat  Dinner     3
239       29.03  5.92    Male     No  Sat  Dinner     3
240       27.18  2.00  Female    Yes  Sat  Dinner     2
241       22.67  2.00    Male    Yes  Sat  Dinner     2
242       17.82  1.75    Male     No  Sat  Dinner     2

[163 rows x 7 columns]

- **between(값1, 값2)**: 값1 ~ 값2까지 범위안의 데이터만 조회한다.

In [33]:
# 범위 지정 (1 <= size <= 3)
tips.loc[tips['size'].between(1,3)]
# tips.loc[tips['size'].between(1,3),:]

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
6          8.77  2.00    Male     No   Sun  Dinner     2
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[198 rows x 7 columns]

- 위 구문은 다음과 같은 의미를 갖는다.

In [34]:
# and
tips.loc[(tips['size']>=1) & (tips['size']<=3)]

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
6          8.77  2.00    Male     No   Sun  Dinner     2
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[198 rows x 7 columns]

**4) 조건을 만족하는 행의 일부 열 조회**

- **df.loc[조건, ['열 이름1', '열 이름2',...]]** 형태로 조회할 열을 리스트로 지정한다.

In [35]:
# 조건에 맞는 하나의 열 조회

tips.loc[tips['size'] >= 5, ['tip']]

      tip
125  4.20
141  6.70
142  5.00
143  5.00
155  5.14
156  5.00
185  5.00
187  2.00
216  3.00

In [ ]:
# 조건에 맞는 여러 열 조회


tips.loc[tips['size'] >= 5, ['tip', 'total_bill']]

In [ ]:
# 가능하지만 비권장
tips.total_bill

0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64

## 3.5.조회 정리

- **데이터프레임 `loc` 조회 예시**

| **조회**        | **코드 예**                                                                                 |
|------------------|--------------------------------------------------------------------------------------------|
| **특정 열**     | df.loc[:, 'score'] → `df['score']`                                                        |
| **여러 열**     | df.loc[:, ['name', 'score']] → `df[['name', 'score']]`                                    |
| **특정 행**     | df.loc[1, :] → `df.loc[1]`                                                               |
| **여러 행**     | df.loc[[1, 3, 5], :] → `df.loc[[1, 3, 5]]`                                               |
| **특정 조건**   | df.loc[df['score'] >= 80, :] → `df.loc[df['score'] >= 80]`                                |
| **여러 조건**   | df.loc[(df['score'] >= 80) & (df['age'] < 20), :] → `df.loc[(df['score'] >= 80) & (df['age'] < 20)]` |
| **여러 조건 특정 열** | `df.loc[(df['score'] >= 80) & (df['age'] < 20), ['name', 'age', 'score']]`                |
| **between()**   | df.loc[df['score'].between(80, 90), :] → `df.loc[df['score'].between(80, 90)]`            |
| **isin()**      | df.loc[df['grp'].isin(['A1', 'B3', 'C1']), :] → `df.loc[df['grp'].isin(['A1', 'B3', 'C1'])]` |

- 원래 코드가 무엇인지 알고 있어야 한다.
- 조건 조회 시 열을 명시하지 않고 조건에 맞는 행 전체를 선택할 경우 loc를 생략할 수 있다.
- df['score'] 를 df.score로 작성할 수 있으나 df['score'] 형태로 사용하기를 권고한다.

## 3.6.인덱스 초기화

- 다음과 같은 경우 인덱스 초기화가 필요하다.
    - 기존 데이터프레임에서 일부 행을 가져와 새로 만든 데이터프레임
    - 일부 행이 지워진 데이터프레임
- 특히 0부터 시작하는 정수형 인덱스의 경우 초기화를 하는 것이 좋다.
- 깔끔한 데이터가 사용하기 좋은 데이터이다.

In [39]:
# tip 열이 6이상인 행 추출
good = tips.loc[tips['tip']>=6]
good

     total_bill    tip     sex smoker   day    time  size
23        39.42   7.58    Male     No   Sat  Dinner     4
47        32.40   6.00    Male     No   Sun  Dinner     4
59        48.27   6.73    Male     No   Sat  Dinner     4
141       34.30   6.70    Male     No  Thur   Lunch     6
170       50.81  10.00    Male    Yes   Sat  Dinner     3
183       23.17   6.50    Male    Yes   Sun  Dinner     4
212       48.33   9.00    Male     No   Sat  Dinner     4
214       28.17   6.50  Female    Yes   Sat  Dinner     3

- **reset_index()** 메소드로 인덱스를 초기화한다.
- 기존 인덱스 값은 의미가 없으므로 drop=True 옵션을 지정해 제거한다.
- inplace=True 옵션을 지정하지 않으면 실제 반영되지 않는다.

In [40]:
good.reset_index(drop=True, inplace=True)

## 3.7. iloc[ ]로 필터링하기
- iloc는 정수 위치(integer location)의 줄임말로 정수값으로 필터링할 때 사용
- loc[ ]와 비슷하지만 필터링할 때 대상을 정수로 짚어내야 하는 점이 다르다.

**- loc와 iloc 특징 및 차이점**

| **기능**      | **loc**               | **iloc**            |
|---------------|------------------------|---------------------|
| **인덱싱 기준** | **라벨(Label)**        | **정수(Integer)**   |
| **범위 선택**   | **포함(inclusive)**    | **제외(exclusive)** |
| **에러 발생**   | 잘못된 라벨 사용 시 에러 | 잘못된 인덱스 사용 시 에러 |
| **속도**      | 조금 느릴 수 있음       | 상대적으로 빠름     |
| **가독성**    | 매우 좋음             | 다소 떨어질 수 있음  |
| **사용 예시**   | `df.loc['2024-01-01']` | `df.iloc[0]`       |

In [41]:
tips.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
# .iloc[] : 데이터 프레임의 행과 열 번호를 사용
# 3번째, 4번째 행(row)과 1번째, 3번째 열을 출력 (2x2)

result = tips.iloc[[2,3],[0,2]]
print(result)

   total_bill   sex
2       21.01  Male
3       23.68  Male